import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'NotoSansDevanagari',
    fontSize: 10,
    lineHeight: 1.5,
    color: '#1f2937',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 10,
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#d97706',
  },
  headerSubtitle: {
    fontSize: 10,
    color: '#6b7280',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 10,
    fontSize: 8,
    color: '#9ca3af',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#b45309',
    marginTop: 15,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#fde68a',
    paddingBottom: 4,
  },
  table: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginBottom: 15,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  tableHeader: {
    backgroundColor: '#fef3c7',
    fontWeight: 'bold',
  },
  tableCol: {
    padding: 6,
    flex: 1,
    borderRightWidth: 1,
    borderRightColor: '#e5e7eb',
  },
  tableColLast: {
    padding: 6,
    flex: 1,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 15,
  },
  gridItem: {
    width: '50%',
    padding: 4,
  },
  label: {
    color: '#6b7280',
    fontSize: 9,
  },
  value: {
    fontWeight: 'bold',
    fontSize: 11,
  },
  disclaimer: {
    marginTop: 20,
    padding: 10,
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    fontSize: 9,
    color: '#6b7280',
    textAlign: 'center',
  },
  alertSuccess: {
    backgroundColor: '#dcfce7',
    color: '#166534',
    padding: 10,
    borderWidth: 1,
    borderColor: '#bbf7d0',
    borderRadius: 4,
    marginBottom: 10,
  },
  alertDanger: {
    backgroundColor: '#fee2e2',
    color: '#991b1b',
    padding: 10,
    borderWidth: 1,
    borderColor: '#fecaca',
    borderRadius: 4,
    marginBottom: 10,
  },
});
